title: <p align="center"> Vaishali Sharma </p>

logo: "/images/photo.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/vaishali.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/i-vaishalisharma27/">LinkedIn</a> |
  <a href="https://public.tableau.com/app/profile/vaishali.sharma5269">Tableau</a>
  </p>
  
  <p align="justify">
  I've done PGP in Data Sciences  and am searching for entry-level positions in the field.I’ve recently worked as an intern under the Data Scientist in Real Estate Company (XANADU REALITY) for two months for further details please refer resume.As for my past experiences ,I worked as JRF in a National Physical Laboratory ,New Delhi.
  </p>
  
theme: jekyll-theme-minimal

