title: <p align="center"> Vaishali Sharma </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/i-vaishalisharma27/">LinkedIn</a> |
  <a href="https://github.com/I-Vaishali">GitHub</a>
  </p>
  
  <p align="justify">
  I'm pursuing my PGP in Data Sciences and am searching for entry-level positions in the field.
  <br><br>
   I’ve recently worked as an intern under the Data Scientist in Real Estate Company (XANADU REALITY) for two months for further details please refer resume.As for my past experiences ,I worked as JRF in a National Lab, my work has provided me exposure to work with the elite companies and deep knowledge of the RF field and various softwares and programming languages.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

